x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 
services:
  #  db:
  #   image: mysql:8
  #   <<: [*deploy-dev, *env_file, *restart]
  #   environment:
  #    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #    - MYSQL_DATABASE=${MYSQL_DATABASE}
  #    - MYSQL_USER=${MYSQL_USER}
  #    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #    - MYSQL_ROOT_HOST="%" # <--- Это вам обязательно понадобится при выполнении ДЗ!
  #   networks:
  #      backend:
  #       ipv4_address: 172.20.0.10
   web:
    build:
      context: .
      dockerfile: ./Dockerfile.python
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - DB_HOST=${db}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.5
include:
  - proxy.yaml
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24